# num1=int(input("Enter your number 1 : "))
# num2=int(input("Enter your number 2 : "))
# num3=int(input("Enter your number 3 : "))
# num4=int(input("Enter your number 4 : "))
# num5=int(input("Enter your number 5 : "))

# a=set()
# a.add(num1)
# a.add(num2)
# a.add(num3)
# a.add(num4)
# a.add(num5)
# print(a)
x=input()
print(x)
print(type(x))